cloud:
  aws:
    region:
      static: ap-south-1
    credentials:
      access-key: 
      secret-key: 
server:
  port: 9997
  

aws:
  paramstore:
    enabled: true
    

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env
